# Production context: all deploys from the Production branch
# set in your site’s Branches settings in the UI will inherit
# these settings. You can define environment variables
# here but we recommend using the Netlify UI for sensitive
# values to keep them out of your source repository.
# specific NPM_VERSION if the used Node version uses a different one that specified in package.json
[context.production]
publish = "dist"
command = "npm run build"
ELEVENTY_PRODUCTION = "true"
environment = { NODE_VERSION = "^22.22.0", NPM_VERSION = "11.7.0", NODE_ENV = "production" }


# Dev context: environment variables set here
# are available for local development environments
# run using Netlify Dev. These values can be
# overwritten on branches that have a more specific
# branch context configured.
[context.dev.environment]
NODE_ENV = "development"
NODE_VERSION = "^22.22.0"
NPM_VERSION = "11.7.0"
ELEVENTY_PRODUCTION = "false"

# Specific branch context: all deploys from
# this specific branch will inherit these settings.
[context.staging.environment] # “staging” is a branch name
NODE_ENV = "production"
NODE_VERSION = "^22.22.0"
NPM_VERSION = "11.7.0"
ELEVENTY_PRODUCTION = "true"
